export const types = {
    //Sync
    FILL_TASKS:                  "FILL_TASKS",
    CREATE_TASK:                 "CREATE_TASK",
    REMOVE_TASK:                 "REMOVE_TASK",
    UPDATE_TASK:                 "UPDATE_TASK",
    UPDATE_TASKS_FILTER:         "UPDATE_TASKS_FILTER",
    COMPLETE_ALL_TASKS:          "COMPLETE_ALL_TASKS",
    UPDATE_NEW_TASK_MESSAGE:     "UPDATE_NEW_TASK_MESSAGE",
    UPDATE_EDITING_TASK_MESSAGE: "UPDATE_EDITING_TASK_MESSAGE",
    CLEAR_EDITING_TASK_MESSAGE:  "CLEAR_EDITING_TASK_MESSAGE",
    TOGGLE_TASK_EDITING:         "TOGGLE_TASK_EDITING",
    SET_EDITING_TASK_ID:         "SET_EDITING_TASK_ID",
    //Async
    FETCH_TASKS_ASYNC:           "FETCH_TASKS_ASYNC",
    CREATE_TASK_ASYNC:           "CREATE_TASK_ASYNC",
    REMOVE_TASK_ASYNC:           "REMOVE_TASK_ASYNC",
    UPDATE_TASK_ASYNC:           "UPDATE_TASK_ASYNC",
    COMPLETE_ALL_TASKS_ASYNC:    "COMPLETE_ALL_TASKS_ASYNC",
};
